"""remove date record

Revision ID: 0697a8162520
Revises: 8cd7b1d2eb13
Create Date: 2026-03-19 14:54:12.195591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0697a8162520'
down_revision: Union[str, Sequence[str], None] = '8cd7b1d2eb13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookmark', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmark', sa.Column('date', sa.DATE(), nullable=False))
    # ### end Alembic commands ###