from fastapi import APIRouter, HTTPException, Query

import logging
import re
from datetime import datetime

from app.helpers.archive_helper import ArchiveHelper


logger = logging.getLogger(__name__)

router = APIRouter()


@router.get("/health")
def health():
    """Health check endpoint to verify archive access and configuration."""
    return {
        "status":       "ok",
        "sds_root":     str(ArchiveHelper.SDS_ROOT),
        "sds_exists":   ArchiveHelper.SDS_ROOT.exists(),
        "station_xml":  str(ArchiveHelper.STATION_XML),
        "xml_exists":   ArchiveHelper.STATION_XML.exists(),
        "network":      ArchiveHelper.NETWORK,
        "station":      ArchiveHelper.STATION,
    }


@router.get("/archive/channels", response_model=list[str])
def get_channels():
    """
    Scan the SDS tree and return all unique channel codes present
    for the configured network/station, e.g. ["EHE", "EHN", "EHZ"].
    """
    if not ArchiveHelper.SDS_ROOT.exists():
        raise HTTPException(status_code=503, detail=f"SDS root not found: {ArchiveHelper.SDS_ROOT}")

    channels: set[str] = set()
    ch_dir_pattern = re.compile(r"^[A-Z]{3}\.D$")

    for year_dir in ArchiveHelper.SDS_ROOT.iterdir():
        if not year_dir.is_dir():
            continue
        sta_dir = year_dir / ArchiveHelper.NETWORK / ArchiveHelper.STATION
        if not sta_dir.is_dir():
            continue
        for ch_dir in sta_dir.iterdir():
            if ch_dir.is_dir() and ch_dir_pattern.match(ch_dir.name):
                channels.add(ch_dir.name.split(".")[0])

    if not channels:
        raise HTTPException(status_code=404, detail="No channels found in archive")

    return sorted(channels)


@router.get("/archive/days", response_model=list[str])
def get_days(
    channel: str = Query(..., description="Channel code, e.g. EHZ"),
):
    """
    Return sorted ISO dates (YYYY-MM-DD) for which at least one SDS day
    file exists for the requested channel.
    """
    days: set[str] = set()
    file_glob = f"{ArchiveHelper.NETWORK}.{ArchiveHelper.STATION}.{ArchiveHelper.LOCATION}.{channel}.D.*"

    for year_dir in ArchiveHelper.SDS_ROOT.iterdir():
        if not year_dir.is_dir():
            continue
        ch_dir = year_dir / ArchiveHelper.NETWORK / ArchiveHelper.STATION / f"{channel}.D"
        if not ch_dir.is_dir():
            continue
        for f in ch_dir.glob(file_glob):
            parts = f.name.split(".")
            if len(parts) < 7:
                continue
            try:
                dt = datetime.strptime(f"{parts[5]} {parts[6]}", "%Y %j")
                days.add(dt.date().isoformat())
            except ValueError:
                continue

    if not days:
        raise HTTPException(
            status_code=404,
            detail=f"No data found for channel {channel!r}",
        )

    return sorted(days)


@router.get("/archive/waveform")
def get_waveform(
    channel: str = Query(...,        description="Channel code, e.g. EHZ"),
    start:   str = Query(...,        description="ISO-8601 start time"),
    end:     str = Query(...,        description="ISO-8601 end time"),
    units:   str = Query("COUNTS",   description="COUNTS | VEL | DISP | ACC"),
    max_pts: int = Query(4000,       description="Max display points (peak-preserving decimation)", ge=100, le=20000),
):
    """
    Return waveform data for the requested channel and time window.

    When units=COUNTS (default) the raw ADC integer samples are returned.
    For VEL / DISP / ACC the instrument response is deconvolved using the
    station.xml generated by rpi-seism, and data is returned in nm, nm/s,
    or nm/s² respectively.

    The response is always peak-decimated to max_pts points for display
    performance — the full resolution is preserved in the archive.
    """
    if units not in ArchiveHelper.UNIT_LABELS:
        raise HTTPException(
            status_code=400,
            detail=f"Invalid units {units!r}. Must be one of: {list(ArchiveHelper.UNIT_LABELS)}",
        )

    t_start = ArchiveHelper.parse_time(start, "start")
    t_end   = ArchiveHelper.parse_time(end,   "end")

    if t_end <= t_start:
        raise HTTPException(status_code=400, detail="end must be after start")

    window_h = (t_end - t_start) / 3600
    if window_h > ArchiveHelper.MAX_WINDOW_H:
        raise HTTPException(
            status_code=400,
            detail=f"Window too large ({window_h:.1f} h). Maximum is {ArchiveHelper.MAX_WINDOW_H} h.",
        )

    #  Read from SDS 
    client = ArchiveHelper.sds_client()

    try:
        st = client.get_waveforms(ArchiveHelper.NETWORK, ArchiveHelper.STATION, ArchiveHelper.LOCATION, channel, t_start, t_end)
    except Exception as exc:
        logger.warning("SDS read failed: %s", exc)
        raise HTTPException(status_code=404, detail=f"Archive read error: {exc}") from exc

    if not st:
        raise HTTPException(
            status_code=404,
            detail=f"No data for {channel} between {start} and {end}",
        )

    st.merge(fill_value=0)
    tr = st[0]

    if tr.stats.npts > ArchiveHelper.MAX_SAMPLES:
        raise HTTPException(
            status_code=400,
            detail=(
                f"Trace contains {tr.stats.npts:,} samples which exceeds the "
                f"{ArchiveHelper.MAX_SAMPLES:,} sample limit. Narrow the time window."
            ),
        )

    logger.info(
        "Serving %s %s [%s - %s] units=%s npts=%d",
        ArchiveHelper.STATION, channel, start, end, units, tr.stats.npts,
    )

    #  Instrument response removal 
    if units != "COUNTS":
        try:
            ArchiveHelper.deconvolve(tr, units)
        except HTTPException:
            raise
        except Exception as exc:
            logger.exception("Deconvolution failed")
            raise HTTPException(
                status_code=500,
                detail=f"Deconvolution failed: {exc}",
            ) from exc

    #  Peak-preserving display decimation 
    data, factor = ArchiveHelper.peak_decimate(tr.data, max_pts)
    display_fs   = tr.stats.sampling_rate / factor

    return {
        "channel":       channel,
        "network":       ArchiveHelper.NETWORK,
        "station":       ArchiveHelper.STATION,
        "units":         ArchiveHelper.UNIT_LABELS[units],
        "fs":            display_fs,
        "starttime":     tr.stats.starttime.isoformat(),
        "endtime":       tr.stats.endtime.isoformat(),
        "npts_raw":      tr.stats.npts,
        "npts_display":  int(len(data)),
        "data":          data.tolist(),
    }


@router.get("/archive/events", response_model=list[dict])
def get_events(
    channel: str = Query(...,  description="Channel code, e.g. EHZ"),
    date:    str = Query(...,  description="ISO date, e.g. 2025-03-23"),
    limit:   int = Query(100,  description="Maximum records to return", ge=1, le=1000),
):
    """
    Return SDS day file records for a specific channel and date.
    Returns a flat list of file metadata dicts.
    """
    if not ArchiveHelper.SDS_ROOT.exists():
        raise HTTPException(status_code=503, detail=f"SDS root not found: {ArchiveHelper.SDS_ROOT}")

    try:
        dt  = datetime.strptime(date, "%Y-%m-%d")
        doy = dt.timetuple().tm_yday
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=f"Invalid date format: {date!r}. Expected YYYY-MM-DD") from exc

    file_re = re.compile(
        rf"^{re.escape(ArchiveHelper.NETWORK)}\."
        rf"{re.escape(ArchiveHelper.STATION)}\."
        rf"{re.escape(ArchiveHelper.LOCATION)}\."
        rf"{re.escape(channel)}\.D\."
        rf"{dt.year}\.{doy:03d}$"
    )

    records: list[dict] = []

    year_dir = ArchiveHelper.SDS_ROOT / str(dt.year)
    ch_dir   = year_dir / ArchiveHelper.NETWORK / ArchiveHelper.STATION / f"{channel}.D"

    if ch_dir.is_dir():
        for f in ch_dir.iterdir():
            if file_re.match(f.name):
                records.append({
                    "date":     date,
                    "channel":  channel,
                    "filename": f.name,
                    "size_kb":  round(f.stat().st_size / 1024, 1),
                })

    records.sort(key=lambda r: r["filename"])
    return records[:limit]
